- name: configure DB server
  hosts: db
  become: yes
  vars: 
    login_host: 107.20.35.219
  vars_prompt:
    name: mysql_root_password
    prompt: please enter password
    private: no
  tasks: 
  - name: installing mysql server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  
  - name: starting mysql service
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: Install bottle python package
    ansible.builtin.pip:
      name: 
      - PyMySql
      - cryptography
      executable: pip3.9

  - name: connection for mysql DB
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
      filter: version
    ignore_errors: yes
    register: output

  - name: connection output
    ansible.builtin.debug:
      msg: "output: {{ output }}"

  - name: setting up root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}"
    when: output.failed is true #don't give {{ }} in when condition